In [13]:
import numpy as np
arr = np.array([[2,3,5,1],
                [5,1,2,8],
                [5,1,6,-1]])
pojedynczy_element = arr[0,3]
pojedynczy_element_od_konca = arr[-3,-1]
kolumna = arr[:,0]
wiersz = arr[2,:]
obszar = arr[0:2,1:4]
obszar_pomijajac_koncowe_indeksy = arr[:2,1:]
parzyste_kolumny = arr[:,::2]
nieparzyste_kolumny = arr[:,1::2]
odwrocone_kolumny = arr[:,::-1]

print(pojedynczy_element)
print(pojedynczy_element_od_konca)
print(kolumna)
print(wiersz)
print(obszar)
print(obszar_pomijajac_koncowe_indeksy)
print(parzyste_kolumny)
print(nieparzyste_kolumny)
print(odwrocone_kolumny)

print("\nNastepne \n")

indeksy = [1, 1, -1]
wybrane_kolumny = arr[:,indeksy]
maska = arr>2
arr_maskowane = arr[maska]


print(wybrane_kolumny)
print(arr_maskowane)

1
1
[2 5 5]
[ 5  1  6 -1]
[[3 5 1]
 [1 2 8]]
[[3 5 1]
 [1 2 8]]
[[2 5]
 [5 2]
 [5 6]]
[[ 3  1]
 [ 1  8]
 [ 1 -1]]
[[ 1  5  3  2]
 [ 8  2  1  5]
 [-1  6  1  5]]

Nastepne 

[[ 3  3  1]
 [ 1  1  8]
 [ 1  1 -1]]
[3 5 5 8 5 6]
